### ISSUE TITLE
Ionic 2 - Engagement not defined

### ISSUE THREAD

**Issue by coreyroth** [Azure/azure-mobile-engagement-cordova#45] opened 2017-01-09 01:17 UTC
I've used the Mobile Engagement plugin successfully with Ionic 1 for some time now, but I am trying to get it working with Ionic 2.  As with any library without typescript definitions, I installed the plugin and then manually declared the reference to Engagement but it doesn't seem to work in this case.  Anyone else have any experience getting it to work?

**Comment by ogoguel** [comment] 2017-01-09 12:41
If you've added the plugin and declared the reference to the Engagement variable, it should work directly in a ionic2 project.

Can you describe more the issue you're facing  ?

Here's a minimum sample that displays the Engagement plugin status in the ionic2 starter project as a starting point :

```
ionic start azme-ionic2 --v2
cd azme-ionic2
ionic plugin add cordova-plugin-ms-azure-mobile-engagement -variable AZME_IOS_CONNECTION_STRING=mystring
#modify the about.html and about.ts files (cf. below)
ionic emulate ios
````
### `azme-ionic2/app/pages/about.html`
```
<ion-header>
  <ion-navbar>
    <ion-title>
      About
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
	plugin version : {{info.pluginVersion}}
</ion-content>

```

### `azme-ionic2/app/pages/about.ts`
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

// To make the Engagement object visible to Typescript
declare var Engagement : any

@Component({
  selector: 'page-about',
  templateUrl: 'about.html'
})
export class AboutPage {

 public info : any

  constructor(public navCtrl: NavController) {
	this.info = {}
  }

  ngOnInit() {  
   let __this : AboutPage = this;
  		if (typeof Engagement != "undefined") {
	  		Engagement.getStatus(function(_info) {
	            __this.info = _info;
	    	});        
	}
  }
}

```

**Comment by gustavokloh** [comment] 2017-01-16 13:23
I have this issue, but not with Ionic 2. I'm still using Ionic 1 and the plugin looks like doesn't work with Cordova 6.4.0. 

Check your cordova version.

**Comment by ogoguel** [comment] 2017-01-18 21:02
There's no known incompatibility of the plugin with Cordova 6.4.0 and Ionic 1/2.

To reproduce your issue, could you provide : your versions of Ionic and Cordova, your target platform, the language used (js or typescript), the plugins installed (besides AZME), and if possible your log files.

**Comment by clpolet** [comment] 2017-10-03 23:17
No news, closing the issue.

**Closed by clpolet** 2017-10-03 23:17 UTC
