### ISSUE TITLE
Limit in 64 characters is too short

### ISSUE THREAD

**Issue by greybax** [Azure/azure-mobile-engagement-cordova#51] opened 2017-02-16 22:15 UTC
I'm using `sendActivity`, `sendSessionEvent`, `sendEvent` and other with first parameter which means name of some action in format as:

    `${rootViewPath}.${someActionName}`

In some cases this generated too long string which do not pass validation of 64 characters.

**Comment by ogoguel** [comment] 2017-02-18 22:13
Unfortunately, this is a limitation of the native SDK and this cannot be fixed in the Cordova SDK.

**Comment by clpolet** [comment] 2017-10-03 21:55
This limitation is by design in the service, also note that the Azure Mobile Engagement service will be retired March 2018.

**Closed by clpolet** 2017-10-03 21:55 UTC
Labels: wontfix
